# Usa l'immagine ufficiale di uv basata su Python slim
FROM astral/uv:python3.12-bookworm-slim


# Imposta la cartella di lavoro nel container
WORKDIR /nicegui_learning

# Abilita l'ottimizzazione del caching dei layer di Docker per uv
ENV UV_COMPILE_BYTECODE=1

# Copia solo i file di configurazione per sfruttare la cache di Docker
COPY pyproject.toml uv.lock ./

# Installa le dipendenze del progetto (salta l'installazione del progetto stesso per ora)
RUN uv sync --frozen --no-install-project --no-dev


# Copia il resto del codice della tua applicazione
COPY app ./app/

# Comando per avviare la tua app NiceGUI (es. main.py)
CMD ["uv", "run", "app/run_web.py"]
