[project]
name = "nicegui-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "asyncpg>=0.31.0",
    "bcrypt>=5.0.0",
    "nicegui>=3.12.1",
    "pydantic[email]>=2.13.4",
    "pywebview>=6.2.1",
    "sqlalchemy>=2.0.50",
]

[tool.uv]
override-dependencies = [
    # Se la piattaforma è Linux (Docker), forza una condizione impossibile 
    # che impedisce l'installazione di pywebview senza rompere macOS/Windows.
    "pywebview ; sys_platform == 'linux' and python_version < '0.0'"
]

[dependency-groups]
dev = [
    "alembic>=1.18.4",
    "psycopg2-binary>=2.9.12",
    "ruff>=0.15.14",
]

[tool.ruff]
line-length = 120

[tool.ruff.format]
quote-style = "single"
indent-style = "tab"
docstring-code-format = true
